In [40]:
#https://www.kaggle.com/fedesoriano/heart-failure-prediction
import pandas as pd
df = pd.read_csv('U:\Courses\Slides\CMP466\codes\Preprocessing\heart.csv')

print(df.shape)
df.describe()

(918, 12)


Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [41]:
df.head(10)#prints the first n rows (default 5)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   
5   39   M           NAP        120          339          0     Normal    170   
6   45   F           ATA        130          237          0     Normal    170   
7   54   M           ATA        110          208          0     Normal    142   
8   37   M           ASY        140          207          0     Normal    130   
9   48   F           ATA        120          284          0     Normal    120   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0  
5              N      0.0       Up             0  
6              N      0.0       Up             0  
7              N      0.0       Up             0  
8              Y      1.5     Flat             1  
9              N      0.0       Up             0

In [42]:
y = df['HeartDisease'].to_numpy() #Extract the labels and put them in y. It has to be an array (not dataframe)

y 


array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [43]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [44]:
df = df.drop(columns=['HeartDisease'])

In [45]:
df.head(5)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  
0              N      0.0       Up  
1              N      1.0     Flat  
2              N      0.0       Up  
3              Y      1.5     Flat  
4              N      0.0       Up

In [46]:
#Applying ordinal/integer encoding on one variable

from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()

df["ChestPainType_code"] = ord_enc.fit_transform(df[["ChestPainType"]])
#df[["ChestPainType", "ChestPainType_code"]].head(10)
df.head(10)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   
5   39   M           NAP        120          339          0     Normal    170   
6   45   F           ATA        130          237          0     Normal    170   
7   54   M           ATA        110          208          0     Normal    142   
8   37   M           ASY        140          207          0     Normal    130   
9   48   F           ATA        120          284          0     Normal    120   

  ExerciseAngina  Oldpeak ST_Slope  ChestPainType_code  
0              N      0.0       Up                 1.0  
1              N      1.0     Flat                 2.0  
2              N      0.0       Up                 1.0  
3              Y      1.5     Flat                 0.0  
4              N      0.0       Up                 2.0  
5              N      0.0       Up                 2.0  
6              N      0.0       Up                 1.0  
7              N      0.0       Up                 1.0  
8              Y      1.5     Flat                 0.0  
9              N      0.0       Up                 1.0

In [47]:
ord_enc.categories_

[array(['ASY', 'ATA', 'NAP', 'TA'], dtype=object)]

In [48]:
#Applying ordinal/integer encoding for multiple variables:

df[["Sex_code", "RestingECG_code"]] = ord_enc.fit_transform(df[["Sex", "RestingECG"]])

#The returned transformed matrix will replace the original columns, as follows:
#df[["Sex", "RestingECG"]] = ord_enc.fit_transform(df[["Sex", "RestingECG"]])

#df[["ChestPainType", "ChestPainType_code"]].head(10)
df.head(10)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   
5   39   M           NAP        120          339          0     Normal    170   
6   45   F           ATA        130          237          0     Normal    170   
7   54   M           ATA        110          208          0     Normal    142   
8   37   M           ASY        140          207          0     Normal    130   
9   48   F           ATA        120          284          0     Normal    120   

  ExerciseAngina  Oldpeak ST_Slope  ChestPainType_code  Sex_code  \
0              N      0.0       Up                 1.0       1.0   
1              N      1.0     Flat                 2.0       0.0   
2              N      0.0       Up                 1.0       1.0   
3              Y      1.5     Flat                 0.0       0.0   
4              N      0.0       Up                 2.0       1.0   
5              N      0.0       Up                 2.0       1.0   
6              N      0.0       Up                 1.0       0.0   
7              N      0.0       Up                 1.0       1.0   
8              Y      1.5     Flat                 0.0       1.0   
9              N      0.0       Up                 1.0       0.0   

   RestingECG_code  
0              1.0  
1              1.0  
2              2.0  
3              1.0  
4              1.0  
5              1.0  
6              1.0  
7              1.0  
8              1.0  
9              1.0

In [49]:
ord_enc.categories_

[array(['F', 'M'], dtype=object), array(['LVH', 'Normal', 'ST'], dtype=object)]

In [50]:
#Apply oneHot encoding
from sklearn.preprocessing import OneHotEncoder

onehot_enc = OneHotEncoder()

onehot_results = onehot_enc.fit_transform(df[["ST_Slope"]])


#pd.DataFrame(onehot_results.toarray(), columns = onehot_enc.categories_).head()

In [51]:
onehot_results

<918x3 sparse matrix of type '<class 'numpy.float64'>'
	with 918 stored elements in Compressed Sparse Row format>

In [52]:
onehot_enc.categories_

[array(['Down', 'Flat', 'Up'], dtype=object)]

In [53]:
#To join this data back to the original dataframe.
df = df.join(pd.DataFrame(onehot_results.toarray(), columns = onehot_enc.categories_))


In [54]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  ChestPainType_code  Sex_code  \
0              N      0.0       Up                 1.0       1.0   
1              N      1.0     Flat                 2.0       0.0   
2              N      0.0       Up                 1.0       1.0   
3              Y      1.5     Flat                 0.0       0.0   
4              N      0.0       Up                 2.0       1.0   

   RestingECG_code  (Down,)  (Flat,)  (Up,)  
0              1.0      0.0      0.0    1.0  
1              1.0      0.0      1.0    0.0  
2              2.0      0.0      0.0    1.0  
3              1.0      0.0      1.0    0.0  
4              1.0      0.0      0.0    1.0

In [55]:
# Pass a list of column names to the columns parameter to drop multiple columns
df = df.drop(columns=['ChestPainType', 'Sex','RestingECG'])


In [56]:
df = df.drop(columns=['ST_Slope']) # to drop a single column

# Pass a list of column numbers to the columns parameter to drop multiple columns
#df.drop(df.columns[[1, 3, 7]], axis=1) #to drop columns 1,3 and 7, axis =1 means accross columns, while axis =0 accross rows

In [57]:
df.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR ExerciseAngina  Oldpeak  \
0   40        140          289          0    172              N      0.0   
1   49        160          180          0    156              N      1.0   
2   37        130          283          0     98              N      0.0   
3   48        138          214          0    108              Y      1.5   
4   54        150          195          0    122              N      0.0   

   ChestPainType_code  Sex_code  RestingECG_code  (Down,)  (Flat,)  (Up,)  
0                 1.0       1.0              1.0      0.0      0.0    1.0  
1                 2.0       0.0              1.0      0.0      1.0    0.0  
2                 1.0       1.0              2.0      0.0      0.0    1.0  
3                 0.0       0.0              1.0      0.0      1.0    0.0  
4                 2.0       1.0              1.0      0.0      0.0    1.0

In [58]:
#how to encode ExerciseAngina ? Use ordinal encoding.. 
#exercise for you

df["ExerciseAngina"] = ord_enc.fit_transform(df[["ExerciseAngina"]])


In [59]:
df.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  ExerciseAngina  Oldpeak  \
0   40        140          289          0    172             0.0      0.0   
1   49        160          180          0    156             0.0      1.0   
2   37        130          283          0     98             0.0      0.0   
3   48        138          214          0    108             1.0      1.5   
4   54        150          195          0    122             0.0      0.0   

   ChestPainType_code  Sex_code  RestingECG_code  (Down,)  (Flat,)  (Up,)  
0                 1.0       1.0              1.0      0.0      0.0    1.0  
1                 2.0       0.0              1.0      0.0      1.0    0.0  
2                 1.0       1.0              2.0      0.0      0.0    1.0  
3                 0.0       0.0              1.0      0.0      1.0    0.0  
4                 2.0       1.0              1.0      0.0      0.0    1.0

In [61]:
X = df.to_numpy() # Put the features in X. It has to be an array (not dataframe)
X

array([[ 40., 140., 289., ...,   0.,   0.,   1.],
       [ 49., 160., 180., ...,   0.,   1.,   0.],
       [ 37., 130., 283., ...,   0.,   0.,   1.],
       ...,
       [ 57., 130., 131., ...,   0.,   1.,   0.],
       [ 57., 130., 236., ...,   0.,   1.,   0.],
       [ 38., 138., 175., ...,   0.,   0.,   1.]])

In [62]:
#Split the data into training and testing.

from sklearn.model_selection import train_test_split

[X_train,X_test,y_train,y_test] = train_test_split(X, y, test_size= 0.2)


In [63]:
#Exercise for you:

#import
from sklearn.tree import DecisionTreeClassifier

#Build a DT classifier
clf = DecisionTreeClassifier()

#Train it using the training set
clf.fit(X_train, y_train)

#Test it using the testing set and find the accuracy score
print(clf.score(X_test,y_test))

#PLot the DT


0.7880434782608695


In [64]:
y_predicted = clf.predict(X_test)


In [65]:
y_predicted

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [66]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)