In [1]:
!python kuzu_main.py --net lin

Train Epoch: 1 [0/60000 (0%)]	Loss: 2.517114
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.972883
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.836119
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.816007
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.450050
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.658963
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.752333
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.692534
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.451993
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.746992
<class 'numpy.ndarray'>
[[736.   4.  10.  15.  32.  70.   4.  71.  34.  24.]
 [  4. 631. 126.  18.  37.  21.  76.  13.  23.  51.]
 [  8.  54. 682.  35.  24.  15.  51.  40.  47.  44.]
 [  5.  37.  64. 741.  13.  47.  14.  21.  42.  16.]
 [ 67.  40.  88.  22. 620.  18.  29.  27.  20.  69.]
 [  9.  29. 152.  20.  24. 687.  31.  11.  25.  12.]
 [  5.  16. 158.  14.  37.  23. 705.  22.  11.   9.]
 [ 13.  29.  27.  16. 109.  18.  66. 550. 114.  58.]
 [ 10.  35. 103.  45.   9.  42.  47.   7. 674.  28.]
 [  8

In [2]:
64*7*7

3136